
artifact:
  branch: "main"
  name: "health_project"
  repo: "https://github.com/nerdcoder/health_project.git"
  version: "v1.0"
build:
  directory: "/home/ec2-user/task/"
  type: "docker"
deploy:
  local-port: 8000
  external-port: 8090
